### ISSUE TITLE
lonely \end{align*}

### ISSUE THREAD

**Issue by agmath** [jonathanforhan/Row-Reducer-MAT-350#6]
Hey Jon -- I can look through the code and submit a pull request to fix this if you'd like. It just looks like you might have a lonely \end{align*} in the source code. I imagine this is probably involved in the feature you have to export the steps used to reduce the augmented matrix in PDF or Markdown format. Thanks for continuing to maintain this resource!

**Comment by jonathanforhan** [comment]
Thank you very much for creating the issue. Sadly MathliveJS makes breaking changes with some frequency creating a sort of moving target. fixed in commit 2cf6dcd

**Comment by jonathanforhan** [comment]
proper mathlivejs versioning using the unpkg versioning tag, added in commit [7d8e774](https://github.com/jonathanforhan/Row-Reducer-MAT-350/commit/7d8e774900bcb0f5507c0ec2b8ab7124bd7129f0) this should fix the versioning issues and should have been done earlier. Thank you for this issue it brought to my attention a bigger problem with version control that should now be fixed with this rollback to mathlivejs@0.95.0, sorry if this caused issues with your lesson plan.
